#define LINES 25
#define COLUMNS_IN_LINE 80
#define BYTES_FOR_EACH_ELEMENT 2
#define SCREENSIZE BYTES_FOR_EACH_ELEMENT * COLUMNS_IN_LINE * LINES

#define IDT_SIZE 256
#define INTERRUPT_GATE 0x8e
#define KERNEL_CODE_SEGMENT_OFFSET 0x08

#define ENTER_KEY_CODE 0x1C
#define MAX_TEXT_SIZE 1024
extern char port_byte_in(int port);

#define MAX_FILES 100
#define MAX_FILE_SIZE 1024
#define MAX_NAME_LENGTH 32